name: "Reusable Deploy Prod"

on:
  workflow_call:
    inputs:
      release_version:
        type: string
        required: false
      repoName:
        type: string
        required: true
      ref:
        type: string
        required: true
      regions:
        type: string
        required: true
      business_group_name:
        type: string
        required: true
      app_mule_environment:
        type: string
        required: true
      secrets_environment:
        type: string
        required: true
      api_name:
        type: string
        required: true
      root_context:
        type: string
        required: true
      api_type:
        type: string
        required: true
      cicd_enabled:
        type: string
        required: true
      app_replicas:
        type: string
        required: true
    # optional: define required secrets here or rely on secrets: inherit
    # secrets:
    #   AZURE_CREDENTIALS:
    #     required: true
``
