#
# This action is run upon a push to main (and can also be triggered manually).
# It dispatches the prod deploy workflow in the CI/CD repository.
#

name: "Deploy to prod"

on:
  workflow_dispatch:
  push:
    branches: [ main ]

# Optional but helpful if you later switch to GITHUB_TOKEN:
# permissions:
#   actions: write
#   contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch deploy_prod in CI/CD repo
        id: dispatch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BOT_USER_TOKEN }}  # PAT with repo + workflow scopes
          script: |
            try {
              const res = await github.rest.actions.createWorkflowDispatch({
                owner: 'Narsing-s',
                repo: 'bank-account-api-ci-cd',
                workflow_id: 'deploy_prod.yml', // must exist under .github/workflows on 'main'
                ref: 'main',
                // If the target workflow expects inputs, pass them as strings:
                // inputs: {
                //   release_version: 'LATEST'
                // }
                inputs: {}
              });
              core.info(`Dispatched deploy_prod.yml -> status: ${res.status}`);
            } catch (error) {
              core.error(`Dispatch failed: ${error.message}`);
              core.setFailed(error);
            }

      - name: Build
        run: |
          echo "Build triggered. Please check the CI/CD repo for the workflow run status."
