// server.js
const express = require("express");
const cors = require("cors");
const axios = require("axios");
const path = require("path");
const https = require("https");
const morgan = require("morgan");
const compression = require("compression");
require("dotenv").config();

const app = express();
const PORT = process.env.PORT || 8080;

// IMPORTANT: Include /api at the end if your Mule listener is /api/*
// Example: https://bank-account-api-xxxxx.5sc6y6-1.usa-e2.cloudhub.io/api
const API_BASE =
  process.env.API_BASE ||
  "https://bank-account-api-xxxxx.5sc6y6-1.usa-e2.cloudhub.io/api";

// Optional (only if API Manager client ID enforcement is enabled)
const CLIENT_ID = process.env.CLIENT_ID || "";
const CLIENT_SECRET = process.env.CLIENT_SECRET || "";

// Keep-alive makes upstream calls more reliable
const httpsAgent = new https.Agent({ keepAlive: true });

// Core middleware
app.use(cors());
app.use(express.json({ limit: "1mb" }));
app.use(compression());
app.use(morgan("tiny"));

/**
 * Serve a safe default /config.js so window.AppConfig is ALWAYS defined
 * This prevents: Cannot read properties of undefined (reading 'WEB_PREFIX')
 *
 * NOTE:
 * - If you later add a real /public/config.js, you can move this route
 *   BELOW express.static so the static file takes precedence.
 * - Do NOT put any secrets in this response; it's sent to the browser.
 */
app.get("/config.js", (_req, res) => {
  const js = `
    // Auto-generated by server to ensure window.AppConfig exists
    window.AppConfig = window.AppConfig || {
      mode: "web",           // "web" (use proxy) or "android" (direct API_BASE)
      WEB_PREFIX: "/api",    // proxy prefix used by the web UI
      ANDROID_BASE: ""       // set only when running in Android mode
    };
  `;
  res.type("application/javascript").send(js);
});

// Health check
app.get("/healthz", (_req, res) => res.status(200).json({ ok: true }));

// Static files (your current UI lives in /public)
// Keep this AFTER /config.js route so the fallback works even if config.js is missing
app.use(express.static(path.join(__dirname, "public")));

/**
 * Proxy: /api/* -> CloudHub (API_BASE)
 * - Forwards method, headers, body, query string.
 * - Passes through status codes and content-type.
 * - Optionally injects client_id/client_secret if provided via env.
 */
app.use("/api", async (req, res) => {
  const upstreamUrl = API_BASE + req.url; // req.url includes /accounts...

  const headers = {
    "Content-Type": req.get("Content-Type") || "application/json",
    Accept: req.get("Accept") || "application/json",
  };
  if (CLIENT_ID) headers["client_id"] = CLIENT_ID;
  if (CLIENT_SECRET) headers["client_secret"] = CLIENT_SECRET;

  try {
    const ax = await axios({
      method: req.method,
      url: upstreamUrl,
      data: ["POST", "PUT", "PATCH"].includes(req.method) ? req.body : undefined,
      headers,
      httpsAgent,
      timeout: 30000,
      validateStatus: () => true, // forward all statuses to the UI
    });

    const ct = ax.headers["content-type"] || "application/json";
    res.status(ax.status).set("Content-Type", ct);
    if (ct.includes("application/json") && typeof ax.data === "object") {
      res.json(ax.data);
    } else {
      res.send(ax.data);
    }
  } catch (e) {
    console.error("Proxy error:", e.message);
    res.status(502).json({ message: "Upstream unavailable", detail: e.message });
  }
});

// SPA fallback: always return index.html for unknown routes (client-side routing)
app.get("*", (_req, res) => {
  res.sendFile(path.join(__dirname, "public", "index.html"));
});

app.listen(PORT, () => {
  console.log(`UI server running on http://localhost:${PORT}`);
  console.log(`Proxy target: ${API_BASE}`);
});
``
